### ISSUE TITLE
gcode program preview doesn't move after touch off

### ISSUE THREAD

**Issue by spaivaras** [qtquickvcp/Cetus#7]
After loading any ngc file, live preview is probably set to 0,0 machine coordinates. And doesn't move when doing touch off on any axis (coordinate origin is moved tho). While doing same operation in axis GUI coordinate origin is moved to current tool location and preview is moved related to touched off position. Is this intended or a bug in preview?

Client tested on all OS'es: OSX sierra, windows 10 64bit, ubuntu 16.04 64bit
machinekit running on debian jessie

**Comment by machinekoder** [comment]
moved to https://github.com/qtquickvcp/Cetus/issues/7
